#' Take an edgelist and create a network of simfrogs with relevant attributes.
#'
#' @param df dataframe generated by uniform.frog.sex.ratio.setup
#' @param adj.matrix adjacency matrix generated by matrixify
#' @param temp numeric value of temperature in degrees celsius
#' @param noiselevel numeric value of noise level used in matrixify
#' @return network of frogs
#' @seealso \code{\link{matrixify}} which this function depends on
#' @export
#'

make.network <- function(df, adj.matrix, temp, noiselevel) {
  # makes a network based on the adj. matrix, temperature, and original df.
  g <- network::network(adj.matrix,
               matrix.type = "adjacency",
               directed = F, ignore.eval = F,
               names.eval = "value")
  network::set.network.attribute(g, "temperature", temp)
  network::set.network.attribute(g, "noise level", noiselevel)
  callrate <- 30 + 1.6*temp
  duration <- 0.2
  male.frogs <- floor(60/(callrate*duration))
  network::set.network.attribute(g, "max male frogs", male.frogs)
  g
}




