#' Ranks males by their attractiveness and removes connections to the lowest-ranked males.
#'
#' @param g network object generated by generate.uniform.frogs
#' @return network object
#' @seealso \code{\link{generate.uniform.frogs}} upon which this function is dependent
#' @export
#'

male.ranker <- function(g) {
  ranks <- function(g, node) {
    df <- as.data.frame(matrix(nrow = 1, ncol = 4))
    names(df) <- c("id.1", "id.2", "atl.na", "value")
    if(length(network::get.edges(g, node)) > 0) {
      for(i in 1:length(network::get.edges(g, node))) {
        work <- unlist(network::get.edges(g, node)[i])
        df[i,] <- work
      }
      df <- arrange(df, desc(value))
      if(nrow(df) <= max.males) {
        df <- df
      } else {
        df[(max.males+1):nrow(df),4] <- 0
      }
    } else {
      dummyvector <- rep(-2, 4)
      df[1,] <- dummyvector
      df[2,] <- dummyvector
    }
    df$atl.na <- NULL
    df
  }
  test <- network::get.vertex.attribute(g, "sex") == "f"
  max.males <- network::get.network.attribute(g, "max male frogs")
  temperature <- network::get.network.attribute(g, "temperature")
  sex.ratio <- network::get.network.attribute(g, "sex ratio")
  x.coord <- network::get.vertex.attribute(g, "x.coord")
  y.coord <- network::get.vertex.attribute(g, "y.coord")
  sex <- network::get.vertex.attribute(g, "sex")
  frequency <- network::get.vertex.attribute(g, "frequency")
  callrate <- network::get.vertex.attribute(g, "callrate")
  noiselevel <- network::get.network.attribute(g, "noise level")
  pondsize <- network::get.network.attribute(g, "pond size")
  node.id <- as.tibble(cbind(network::get.vertex.attribute(g, "vertex.names"), sex))
  names(node.id) <- c("id", "sex")
  node.id$id <- as.numeric(as.character(node.id$id))
  females <- node.id[test,]
  datalist <- list()
  for(i in 1:nrow(females)) {
    working.data <- ranks(g, females$id[i])
    datalist[[i]] <- working.data
  }
  new.edgelist <- do.call(rbind, datalist)
  new.edgelist.no.zero <- dplyr::filter(new.edgelist, value > 0)
  g.new <- network::network.initialize(network::network.size(g), directed = F)
  network::network.vertex.names(g.new) <- network::network.vertex.names(g)
  g.new[as.matrix(new.edgelist.no.zero)] <- 1
  network::set.edge.value(g.new, "value", new.edgelist.no.zero$value)
  network::set.vertex.attribute(g.new, "sex", sex)
  network::set.vertex.attribute(g.new,"x.coord", x.coord)
  network::set.vertex.attribute(g.new, "y.coord", y.coord)
  network::set.vertex.attribute(g.new, "frequency", frequency)
  network::set.vertex.attribute(g.new, "callrate", callrate)
  network::set.network.attribute(g.new, "max male frogs", max.males)
  network::set.network.attribute(g.new, "temperature", temperature)
  network::set.network.attribute(g.new, "sex ratio", sex.ratio)
  network::set.network.attribute(g.new, "noise level", noiselevel)
  network::set.network.attribute(g.new, "pond size", pondsize)
  g.new
}
