#' Ranks males by their attractiveness and removes connections to the lowest-ranked males.
#'
#' @param g network object generated by generate.uniform.frogs
#' @return network object
#' @seealso \code{\link{generate.uniform.frogs}} upon which this function is dependent
#' @export
#'

male.ranker <- function(g) {
  ranks <- function(g, node) {
    df <- as.data.frame(matrix(nrow = 1, ncol = 4))
    names(df) <- c("id.1", "id.2", "atl.na", "value")
    if(length(get.edges(g, node)) > 0) {
      for(i in 1:length(get.edges(g, node))) {
        work <- unlist(get.edges(g, node)[i])
        df[i,] <- work
      }
      df <- arrange(df, desc(value))
      if(nrow(df) <= max.males) {
        df <- df
      } else {
        df[(max.males+1):nrow(df),4] <- 0
      }
    } else {
      dummyvector <- rep(-2, 4)
      df[1,] <- dummyvector
      df[2,] <- dummyvector
    }
    df$atl.na <- NULL
    df
  }
  test <- g %v% "sex" == "f"
  max.males <- g %n% "max male frogs"
  temperature <- g %n% "temperature"
  sex.ratio <- g %n% "sex ratio"
  x.coord <- g %v% "x.coord"
  y.coord <- g %v% "y.coord"
  sex <- g %v% "sex"
  noiselevel <- g %n% "noise level"
  node.id <- as.data.frame(cbind(g %v% "vertex.names", sex))
  names(node.id) <- c("id", "sex")
  node.id$id <- as.numeric(as.character(node.id$id))
  females <- node.id[test,]
  datalist <- list()
  for(i in 1:nrow(females)) {
    working.data <- ranks(g, females$id[i])
    datalist[[i]] <- working.data
  }
  new.edgelist <- do.call(rbind, datalist)
  new.edgelist.no.zero <- dplyr::filter(new.edgelist, value > 0)
  g.new <- network.initialize(network.size(g), directed = F)
  network.vertex.names(g.new) <- network.vertex.names(g)
  g.new[as.matrix(new.edgelist.no.zero)] <- 1
  set.edge.value(g.new, "value", new.edgelist.no.zero$value)
  g.new %v% "sex" <- sex
  g.new %v% "x.coord" <- x.coord
  g.new %v% "y.coord" <- y.coord
  set.network.attribute(g.new, "max male frogs", max.males)
  set.network.attribute(g.new, "temperature", temperature)
  set.network.attribute(g.new, "sex ratio", sex.ratio)
  set.network.attribute(g.new, "noise level", noiselevel)
  g.new
}
